// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzSUeKdPXTAEi9fbqwsX7Xv4h8gZW_nVA',
    appId: '1:354506687825:web:2e20cfe3710148bc15ff70',
    messagingSenderId: '354506687825',
    projectId: 'entregas-internas',
    authDomain: 'entregas-internas.firebaseapp.com',
    storageBucket: 'entregas-internas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRekOYgROSuqlTPdjPUt-zENGYMRr6brk',
    appId: '1:354506687825:android:5e9f8e938d029c2b15ff70',
    messagingSenderId: '354506687825',
    projectId: 'entregas-internas',
    storageBucket: 'entregas-internas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALycWVXLykPiFUuTH_yivq-f8fzjOMLSI',
    appId: '1:354506687825:ios:29d29d2b793be0b615ff70',
    messagingSenderId: '354506687825',
    projectId: 'entregas-internas',
    storageBucket: 'entregas-internas.firebasestorage.app',
    iosClientId: '354506687825-nq2dbh5au0p0cjll6qe6n5rsvq17didu.apps.googleusercontent.com',
    iosBundleId: 'com.suaempresa.entregasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALycWVXLykPiFUuTH_yivq-f8fzjOMLSI',
    appId: '1:354506687825:ios:29d29d2b793be0b615ff70',
    messagingSenderId: '354506687825',
    projectId: 'entregas-internas',
    storageBucket: 'entregas-internas.firebasestorage.app',
    iosClientId: '354506687825-nq2dbh5au0p0cjll6qe6n5rsvq17didu.apps.googleusercontent.com',
    iosBundleId: 'com.suaempresa.entregasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzSUeKdPXTAEi9fbqwsX7Xv4h8gZW_nVA',
    appId: '1:354506687825:web:be40972245efd60315ff70',
    messagingSenderId: '354506687825',
    projectId: 'entregas-internas',
    authDomain: 'entregas-internas.firebaseapp.com',
    storageBucket: 'entregas-internas.firebasestorage.app',
  );
}
